#define	LUAMONGO_CONNECTION	"mongo.Connection"
#define	LUAMONGO_CURSOR		"mongo.Cursor"

#define	LUAMONGO_ERR_CONNECTION_FAILED	"Connection failed: %s"
#define	LUAMONGO_ERR_QUERY_FAILED	"Query failed: %s"
#define	LUAMONGO_ERR_INSERT_FAILED	"Insert failed: %s"
#define	LUAMONGO_ERR_CONNECT_FAILED	"Connection to %s failed: %s"
#define	LUAMONGO_ERR_COUNT_FAILED	"Count failed: %s"
#define	LUAMONGO_ERR_REMOVE_FAILED	"Remove failed: %s"
#define	LUAMONGO_ERR_UPDATE_FAILED	"Update failed: %s"
#define	LUAMONGO_UNSUPPORTED_BSON_TYPE	"Unsupported BSON type"
#define	LUAMONGO_UNSUPPORTED_LUA_TYPE	"Unsupported Lua type `%s'"
#define	LUAMONGO_REQUIRES_JSON_OR_TABLE	"JSON string or Lua table required"
